on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
env:
  GITHUB_TOKEN: ${{ secrets.AUTOPROJECT }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to Triage
    steps:
    - name: Put new issues and pull requests into triage
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/orgs/havenstadrp/projects/8'
        column_name: 'New'